In [1]:
import torch

x = torch.tensor([-5, -2, 0, 2, 5])
y = torch.relu(x)
print(y)

tensor([0, 0, 0, 2, 5])


In [8]:
def my_relu(x):
    result = []
    for i in x:
        result.append(max(0, i.item()));
    return torch.tensor(result)
    
y = my_relu(x)
print(y)

tensor([0, 0, 0, 2, 5])


In [9]:
def torch_relu(x):
    return torch.maximum(x, torch.tensor(0.0))
    
print(torch_relu(x))

tensor([0., 0., 0., 2., 5.])


In [11]:
x = torch.tensor(-6.0, requires_grad = True)
y = torch.relu(x)

y.backward()
x.grad

tensor(0.)

In [12]:
x = torch.tensor(6.0, requires_grad = True)
y = torch.relu(x)

y.backward()
x.grad

tensor(1.)

In [15]:
import torch

x = torch.tensor([2.0, 5.0])

# input neuron

w1 = torch.tensor([
    [0.5, 0.2],
    [0.3, 0.8],
    [0.9, 0.1]
])

b1 = torch.tensor([
    0.1,
    0.2,
    0.3
])

hidden_layer = w1 @ x + b1
print(hidden_layer)

tensor([2.1000, 4.8000, 2.6000])


In [16]:
hidden_layer = torch.relu(hidden_layer)
print(hidden_layer)

tensor([2.1000, 4.8000, 2.6000])


In [17]:
# output neuron
w2 = torch.tensor([0.4, 0.6, 0.2])
b2 = torch.tensor(0.5)

output = w2 @ hidden_layer + b2
print(output)

tensor(4.7400)
