In [1]:
import sys
print(sys.executable)

C:\Users\priya\anaconda3\python.exe


In [2]:
!{sys.executable} -m pip install torch torchvision torchaudio

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/123.0 MB 4.3 MB/s eta 0:00:29
   ---------------------------------------- 0.5/123.0 MB 6.0 MB/s eta 0:00:21
   ---------------------------------------- 0.9/123.0 MB 7.0 MB/s eta 0:00:18
   ---------------------------------------- 1.1/123.0 MB 6.1 MB/s eta 0:00:21
   ---------------------------------------- 1.2/123.0 MB 5.6 MB/s eta 0:00:22
   ---------------------------------------- 1.4/123.0 MB 5.3 MB/s eta 0:00:23
   ---------------------------------------- 1.4/123.0 MB 5.4 MB/s eta 0:00:23
   ---------------------------------------- 1.4/123.0 MB 5.4 MB/s eta 0:00:23
    --------------------------------------- 1.6/123.0 MB 3.8 MB/s eta 0:00:32
    --------------------------------------- 2.2/123.0 MB 4.7 MB/s eta 0:00:26
    --------------------------------------- 2.3/123.0 MB 4.6 MB/s eta 0:00:27
    -----

In [4]:
import torch
print(torch.__version__)
print(torch.tensor([1, 2, 3]))

2.12.0+cpu
tensor([1, 2, 3])


In [9]:
x = torch.tensor([5.0, 8.0])
print(x)
print(x.shape)
print(x.dtype)

tensor([5., 8.])
torch.Size([2])
torch.float32


In [10]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
print(a+b)
print(a*b)

tensor([4, 6])
tensor([3, 8])


In [12]:
print(a.sum())

tensor(3)


In [13]:
import torch

#Inputs 
x = torch.tensor([5.0, 8.0])

#Weights
w = torch.tensor([0.6, 0.2])

#Bias 
b = torch.tensor(1.0)

# Neuron output
y = (x*w).sum() + b

print(y)

tensor(5.6000)


In [14]:
target = torch.tensor(8.0)

loss = (y - target)**2

print(loss)

tensor(5.7600)


In [15]:
w = torch.tensor([0.6, 0.2], requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)

In [3]:
import torch

x = torch.tensor([5.0, 8.0])

w = torch.tensor([0.6, 0.2], requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)

y = (x*w).sum() + b
print("y: ", y)

target = torch.tensor(8.0)

loss = (y-target)**2
loss.backward()

print("loss: ", loss)
print("loss requires gradient: ", loss.requires_grad)
print("w: ", w.grad)
print("b: ", b.grad)

y:  tensor(5.6000, grad_fn=<AddBackward0>)
loss:  tensor(5.7600, grad_fn=<PowBackward0>)
loss requires gradient:  True
w:  tensor([-24.0000, -38.4000])
b:  tensor(-4.8000)


In [4]:
with torch.no_grad():
    w -= 0.01 * w.grad
    b -= 0.01 * b.grad

print("new w: ", w)
print("new b: ", b)

new w:  tensor([0.8400, 0.5840], requires_grad=True)
new b:  tensor(1.0480, requires_grad=True)


In [5]:
y = (x * w).sum() + b

loss = (y - target) ** 2

print(y)
print(loss)

tensor(9.9200, grad_fn=<AddBackward0>)
tensor(3.6864, grad_fn=<PowBackward0>)


In [7]:
print(w.grad, b.grad) # I didn't do loss.backward so it ramins same 

tensor([-24.0000, -38.4000]) tensor(-4.8000)


In [8]:
w.grad.zero_()
b.grad.zero_()

tensor(0.)

In [9]:
print(w.grad, b.grad)

tensor([0., 0.]) tensor(0.)


In [10]:
#Using loop

x = torch.tensor([5.0, 8.0])

w = torch.tensor([0.6, 0.2], requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)

target = torch.tensor(8.0)

lr = 0.01

for epoch in range(20):
    # Forward pass
    y = (x*w).sum() + b
    loss = (y - target)**2

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        w -= lr*w.grad
        b -= lr*b.grad

    # Clear gradients
    w.grad.zero_()
    b.grad.zero_()

    print(
        f"Epoch {epoch+1: 2d} | "
        f"Prediction = {y.item():.4f} | "
        f"Loss = {loss.item():.4f}"
    )

Epoch  1 | Prediction = 5.6000 | Loss = 5.7600
Epoch  2 | Prediction = 9.9200 | Loss = 3.6864
Epoch  3 | Prediction = 6.4640 | Loss = 2.3593
Epoch  4 | Prediction = 9.2288 | Loss = 1.5099
Epoch  5 | Prediction = 7.0170 | Loss = 0.9664
Epoch  6 | Prediction = 8.7864 | Loss = 0.6185
Epoch  7 | Prediction = 7.3709 | Loss = 0.3958
Epoch  8 | Prediction = 8.5033 | Loss = 0.2533
Epoch  9 | Prediction = 7.5973 | Loss = 0.1621
Epoch  10 | Prediction = 8.3221 | Loss = 0.1038
Epoch  11 | Prediction = 7.7423 | Loss = 0.0664
Epoch  12 | Prediction = 8.2062 | Loss = 0.0425
Epoch  13 | Prediction = 7.8351 | Loss = 0.0272
Epoch  14 | Prediction = 8.1319 | Loss = 0.0174
Epoch  15 | Prediction = 7.8944 | Loss = 0.0111
Epoch  16 | Prediction = 8.0844 | Loss = 0.0071
Epoch  17 | Prediction = 7.9324 | Loss = 0.0046
Epoch  18 | Prediction = 8.0540 | Loss = 0.0029
Epoch  19 | Prediction = 7.9568 | Loss = 0.0019
Epoch  20 | Prediction = 8.0346 | Loss = 0.0012


In [12]:
X = torch.tensor([
    [1.0, 2.0],
    [2.0, 3.0],
    [3.0, 4.0],
    [4.0, 5.0]
])

y_true = torch.tensor([
    3.0,
    5.0,
    7.0,
    9.0
])

print(X.shape)
print(y_true.shape)

torch.Size([4, 2])
torch.Size([4])


In [21]:
w = torch.tensor([0.3, -0.5], requires_grad = True)
b = torch.tensor(2.0, requires_grad = True)

lr = 0.01

for epoch in range(1000):
    y_pred = X@w + b
    loss = ((y_pred - y_true) ** 2).mean()

    loss.backward()
    with torch.no_grad():
        w -= lr*w.grad
        b -= lr*b.grad

    w.grad.zero_()
    b.grad.zero_()

    print(
        f"Epoch {epoch+1: 2d} | "
        f"Prediction = {y_pred} | "
        f"Loss = {loss.item():.4f}"
    )

Epoch  1 | Prediction = tensor([1.3000, 1.1000, 0.9000, 0.7000], grad_fn=<AddBackward0>) | Loss = 31.0500
Epoch  2 | Prediction = tensor([2.5150, 3.0250, 3.5350, 4.0450], grad_fn=<AddBackward0>) | Loss = 10.1735
Epoch  3 | Prediction = tensor([3.1979, 4.1089, 5.0198, 5.9306], grad_fn=<AddBackward0>) | Loss = 3.5439
Epoch  4 | Prediction = tensor([3.5811, 4.7188, 5.8564, 6.9940], grad_fn=<AddBackward0>) | Loss = 1.4371
Epoch  5 | Prediction = tensor([3.7954, 5.0617, 6.3279, 7.5942], grad_fn=<AddBackward0>) | Loss = 0.7662
Epoch  6 | Prediction = tensor([3.9145, 5.2541, 6.5937, 7.9332], grad_fn=<AddBackward0>) | Loss = 0.5510
Epoch  7 | Prediction = tensor([3.9801, 5.3618, 6.7435, 8.1252], grad_fn=<AddBackward0>) | Loss = 0.4806
Epoch  8 | Prediction = tensor([4.0154, 5.4217, 6.8280, 8.2343], grad_fn=<AddBackward0>) | Loss = 0.4562
Epoch  9 | Prediction = tensor([4.0337, 5.4547, 6.8757, 8.2967], grad_fn=<AddBackward0>) | Loss = 0.4463
Epoch  10 | Prediction = tensor([4.0424, 5.4726, 6.90

In [24]:
print(w)
print(b)

tensor([1.9032, 0.0783], requires_grad=True)
tensor(0.9751, requires_grad=True)
